// <auto-generated />
using System;
using Core.Infraestructura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Core.Infraestructura.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211109110323_fecha pago y recibido nullable")]
    partial class fechapagoyrecibidonullable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Core.Dominio.AggregatesModel.Articulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArticuloEstado")
                        .HasColumnType("int");

                    b.Property<string>("CodigoArticulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdArticuloCategoria")
                        .HasColumnType("int");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecioMayorista")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioMinorista")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TalleArticulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdArticuloCategoria");

                    b.ToTable("Articulos");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.ArticuloCategoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ArticulosCategoria");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.ArticuloStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreadoPor")
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("EsReposicionAutomatica")
                        .HasColumnType("bit");

                    b.Property<bool>("EsReposicionPorLote")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdArticulo")
                        .HasColumnType("int");

                    b.Property<int?>("IdProveedorPreferido")
                        .HasColumnType("int");

                    b.Property<int>("IdSucursal")
                        .HasColumnType("int");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("varchar(50)");

                    b.Property<double>("StockMinimo")
                        .HasColumnType("float");

                    b.Property<double>("StockTotal")
                        .HasColumnType("float");

                    b.Property<int>("TamañoLote")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdArticulo");

                    b.HasIndex("IdProveedorPreferido");

                    b.HasIndex("IdSucursal");

                    b.ToTable("ArticulosStock");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.CajaSucursal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreadoPor")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdSucursal")
                        .HasColumnType("int");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdSucursal");

                    b.ToTable("CajaSucursales");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CUIT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contacto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.ClienteCuentaCorriente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreadoPor")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdVenta")
                        .HasColumnType("int");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("MontoPercibido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("PagoAcreditado")
                        .HasColumnType("bit");

                    b.Property<int>("TipoPago")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdVenta");

                    b.ToTable("ClientesCuentaCorriente");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.CompraArticulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreadoPor")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaPagado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRecibido")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("int");

                    b.Property<int>("IdSucursal")
                        .HasColumnType("int");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("NroRemito")
                        .HasColumnType("bigint");

                    b.Property<bool>("Pagado")
                        .HasColumnType("bit");

                    b.Property<decimal>("Recibido")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdProveedor");

                    b.HasIndex("IdSucursal");

                    b.ToTable("ComprasArticulos");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.CompraArticuloDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdArticulo")
                        .HasColumnType("int");

                    b.Property<int>("IdCompraArticulo")
                        .HasColumnType("int");

                    b.Property<int>("IdProveedorSugerido")
                        .HasColumnType("int");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdArticulo");

                    b.HasIndex("IdCompraArticulo");

                    b.HasIndex("IdProveedorSugerido");

                    b.ToTable("CompraArticuloDetalles");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.CompraInsumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreadoPor")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaPagado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRecibido")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("int");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("NroRemito")
                        .HasColumnType("bigint");

                    b.Property<bool>("Pagado")
                        .HasColumnType("bit");

                    b.Property<decimal>("Recibido")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdProveedor");

                    b.ToTable("ComprasInsumos");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.CompraInsumoDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCompraInsumo")
                        .HasColumnType("int");

                    b.Property<int>("IdInsumo")
                        .HasColumnType("int");

                    b.Property<int>("IdProveedorSugerido")
                        .HasColumnType("int");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdCompraInsumo");

                    b.HasIndex("IdInsumo");

                    b.HasIndex("IdProveedorSugerido");

                    b.ToTable("CompraInsumoDetalles");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.EtapaOrdenProduccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EtapasOrdenProduccion");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            CreadoPor = "Initial",
                            Descripcion = "Cortado",
                            FechaCreacion = new DateTime(2021, 11, 9, 8, 3, 22, 711, DateTimeKind.Local).AddTicks(5604),
                            Orden = 1
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            CreadoPor = "Initial",
                            Descripcion = "Aparado",
                            FechaCreacion = new DateTime(2021, 11, 9, 8, 3, 22, 711, DateTimeKind.Local).AddTicks(5846),
                            Orden = 2
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            CreadoPor = "Initial",
                            Descripcion = "Preparacion",
                            FechaCreacion = new DateTime(2021, 11, 9, 8, 3, 22, 711, DateTimeKind.Local).AddTicks(5855),
                            Orden = 3
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            CreadoPor = "Initial",
                            Descripcion = "Montado",
                            FechaCreacion = new DateTime(2021, 11, 9, 8, 3, 22, 711, DateTimeKind.Local).AddTicks(5858),
                            Orden = 4
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            CreadoPor = "Initial",
                            Descripcion = "Pegado",
                            FechaCreacion = new DateTime(2021, 11, 9, 8, 3, 22, 711, DateTimeKind.Local).AddTicks(5861),
                            Orden = 5
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            CreadoPor = "Initial",
                            Descripcion = "Terminado ",
                            FechaCreacion = new DateTime(2021, 11, 9, 8, 3, 22, 711, DateTimeKind.Local).AddTicks(5864),
                            Orden = 6
                        });
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.Insumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreadoPor")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdProveedorPreferido")
                        .HasColumnType("int");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("StockReservado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StockTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdProveedorPreferido");

                    b.ToTable("Insumos");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.MovimientoStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdArticulo")
                        .HasColumnType("int");

                    b.Property<int>("IdSucursalDestino")
                        .HasColumnType("int");

                    b.Property<int>("IdSucursalOrigen")
                        .HasColumnType("int");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdArticulo");

                    b.HasIndex("IdSucursalDestino");

                    b.HasIndex("IdSucursalOrigen");

                    b.ToTable("MovimientosStock");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.OrdenProduccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CantidadFabricada")
                        .HasColumnType("int");

                    b.Property<int>("CantidadTotal")
                        .HasColumnType("int");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("EstadoEtapaOrdenProduccion")
                        .HasColumnType("int");

                    b.Property<int>("EstadoOrdenProduccion")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdArticulo")
                        .HasColumnType("int");

                    b.Property<int>("IdEtapaOrdenProduccion")
                        .HasColumnType("int");

                    b.Property<int>("IdSolicitudDetalle")
                        .HasColumnType("int");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdArticulo");

                    b.HasIndex("IdEtapaOrdenProduccion");

                    b.HasIndex("IdSolicitudDetalle");

                    b.ToTable("OrdenesProduccion");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.OrdenProduccionEvento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CantidadFabricada")
                        .HasColumnType("int");

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("EstadoEtapaOrdenProduccion")
                        .HasColumnType("int");

                    b.Property<int>("EstadoOrdenProduccion")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEtapaOrdenProduccion")
                        .HasColumnType("int");

                    b.Property<int>("IdOrdenProduccion")
                        .HasColumnType("int");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdEtapaOrdenProduccion");

                    b.HasIndex("IdOrdenProduccion");

                    b.ToTable("OrdenesProduccionEventos");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CUIT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Calificacion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsFabrica")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Proveedores");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            CUIT = "30709834904",
                            Calificacion = 0m,
                            CreadoPor = "Initial",
                            Direccion = "4562 Hazy Panda Limits, Chair Crossing, Kentucky, US, 607898",
                            Email = "TrifulcaLightFoot@gmail.com",
                            EsFabrica = true,
                            FechaCreacion = new DateTime(2021, 11, 9, 8, 3, 22, 712, DateTimeKind.Local).AddTicks(6885),
                            Nombre = "Fabrica LightFoot",
                            Telefono = "+541136558997"
                        });
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.ProveedorArticulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreadoPor")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdArticulo")
                        .HasColumnType("int");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("int");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdArticulo");

                    b.HasIndex("IdProveedor");

                    b.ToTable("ProveedoresArticulos");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.ProveedorArticuloCuentaCorriente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreadoPor")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCompraArticulo")
                        .HasColumnType("int");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("int");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("MontoPagado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TipoPago")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdCompraArticulo");

                    b.HasIndex("IdProveedor");

                    b.ToTable("ProveedoresArticulosCuentaCorriente");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.ProveedorArticuloHistorico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreadoPor")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdArticulo")
                        .HasColumnType("int");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("int");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdArticulo");

                    b.HasIndex("IdProveedor");

                    b.ToTable("ProveedoresArticulosHistorico");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.ProveedorInsumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreadoPor")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdInsumo")
                        .HasColumnType("int");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("int");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdInsumo");

                    b.HasIndex("IdProveedor");

                    b.ToTable("ProveedoresInsumos");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.ProveedorInsumoCuentaCorriente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreadoPor")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCompraInsumo")
                        .HasColumnType("int");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("int");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("MontoPagado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TipoPago")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdCompraInsumo");

                    b.HasIndex("IdProveedor");

                    b.ToTable("ProveedoresInsumosCuentaCorriente");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.ProveedorInsumoHistorico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreadoPor")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdInsumo")
                        .HasColumnType("int");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("int");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdInsumo");

                    b.HasIndex("IdProveedor");

                    b.ToTable("ProveedoresInsumosHistorico");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.Receta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdArticulo")
                        .HasColumnType("int");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdArticulo");

                    b.ToTable("Recetas");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.RecetaDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEtapaOrdenProduccion")
                        .HasColumnType("int");

                    b.Property<int>("IdInsumo")
                        .HasColumnType("int");

                    b.Property<int>("IdReceta")
                        .HasColumnType("int");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdEtapaOrdenProduccion");

                    b.HasIndex("IdInsumo");

                    b.HasIndex("IdReceta");

                    b.ToTable("RecetaDetalles");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.Solicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("EstadoSolicitud")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdSucursal")
                        .HasColumnType("int");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdSucursal");

                    b.ToTable("Solicitudes");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.SolicitudDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CantidadSolicitada")
                        .HasColumnType("int");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdArticulo")
                        .HasColumnType("int");

                    b.Property<int>("IdSolicitud")
                        .HasColumnType("int");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Motivo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdArticulo");

                    b.HasIndex("IdSolicitud");

                    b.ToTable("SolicitudDetalles");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.SolicitudEvento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("EstadoSolicitud")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdSolicitud")
                        .HasColumnType("int");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdSolicitud");

                    b.ToTable("SolicitudEventos");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.Sucursal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sucursales");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioRol")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.UsuarioApi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("UsuariosApi");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreadoPor")
                        .HasColumnType("varchar(50)");

                    b.Property<double>("Descuento")
                        .HasColumnType("float");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdSucursal")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VentaTipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdSucursal");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.VentaDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdArticulo")
                        .HasColumnType("int");

                    b.Property<int>("IdVenta")
                        .HasColumnType("int");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdArticulo");

                    b.HasIndex("IdVenta");

                    b.ToTable("VentasDetalle");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.Articulo", b =>
                {
                    b.HasOne("Core.Dominio.AggregatesModel.ArticuloCategoria", "ArticuloCategoria")
                        .WithMany("Articulos")
                        .HasForeignKey("IdArticuloCategoria")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ArticuloCategoria");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.ArticuloStock", b =>
                {
                    b.HasOne("Core.Dominio.AggregatesModel.Articulo", "Articulo")
                        .WithMany("ArticuloStock")
                        .HasForeignKey("IdArticulo")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Core.Dominio.AggregatesModel.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("IdProveedorPreferido")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Core.Dominio.AggregatesModel.Sucursal", "Sucursal")
                        .WithMany("ArticulosStock")
                        .HasForeignKey("IdSucursal")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("Proveedor");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.CajaSucursal", b =>
                {
                    b.HasOne("Core.Dominio.AggregatesModel.Sucursal", "Sucursal")
                        .WithMany("CajaSucursal")
                        .HasForeignKey("IdSucursal")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.ClienteCuentaCorriente", b =>
                {
                    b.HasOne("Core.Dominio.AggregatesModel.Cliente", "Cliente")
                        .WithMany("ClienteCuentaCorriente")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Core.Dominio.AggregatesModel.Venta", "Venta")
                        .WithMany()
                        .HasForeignKey("IdVenta")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.CompraArticulo", b =>
                {
                    b.HasOne("Core.Dominio.AggregatesModel.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Core.Dominio.AggregatesModel.Sucursal", "Sucursal")
                        .WithMany("CompraArticulos")
                        .HasForeignKey("IdSucursal")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Proveedor");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.CompraArticuloDetalle", b =>
                {
                    b.HasOne("Core.Dominio.AggregatesModel.Articulo", "Articulo")
                        .WithMany()
                        .HasForeignKey("IdArticulo")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Core.Dominio.AggregatesModel.CompraArticulo", "CompraArticulo")
                        .WithMany("CompraArticuloDetalles")
                        .HasForeignKey("IdCompraArticulo")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Core.Dominio.AggregatesModel.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("IdProveedorSugerido")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("CompraArticulo");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.CompraInsumo", b =>
                {
                    b.HasOne("Core.Dominio.AggregatesModel.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.CompraInsumoDetalle", b =>
                {
                    b.HasOne("Core.Dominio.AggregatesModel.CompraInsumo", "CompraInsumo")
                        .WithMany("CompraInsumoDetalles")
                        .HasForeignKey("IdCompraInsumo")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Core.Dominio.AggregatesModel.Insumo", "Insumo")
                        .WithMany()
                        .HasForeignKey("IdInsumo")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Core.Dominio.AggregatesModel.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("IdProveedorSugerido")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CompraInsumo");

                    b.Navigation("Insumo");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.Insumo", b =>
                {
                    b.HasOne("Core.Dominio.AggregatesModel.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("IdProveedorPreferido")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.MovimientoStock", b =>
                {
                    b.HasOne("Core.Dominio.AggregatesModel.Articulo", "Articulo")
                        .WithMany()
                        .HasForeignKey("IdArticulo")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Core.Dominio.AggregatesModel.Sucursal", "SucursalDestino")
                        .WithMany()
                        .HasForeignKey("IdSucursalDestino")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Core.Dominio.AggregatesModel.Sucursal", "SucursalOrigen")
                        .WithMany()
                        .HasForeignKey("IdSucursalOrigen")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("SucursalDestino");

                    b.Navigation("SucursalOrigen");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.OrdenProduccion", b =>
                {
                    b.HasOne("Core.Dominio.AggregatesModel.Articulo", "Articulo")
                        .WithMany()
                        .HasForeignKey("IdArticulo")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Core.Dominio.AggregatesModel.EtapaOrdenProduccion", "EtapaOrdenProduccion")
                        .WithMany()
                        .HasForeignKey("IdEtapaOrdenProduccion")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Core.Dominio.AggregatesModel.SolicitudDetalle", "SolicitudDetalle")
                        .WithMany("OrdenesProduccion")
                        .HasForeignKey("IdSolicitudDetalle")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("EtapaOrdenProduccion");

                    b.Navigation("SolicitudDetalle");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.OrdenProduccionEvento", b =>
                {
                    b.HasOne("Core.Dominio.AggregatesModel.EtapaOrdenProduccion", "EtapaOrdenProduccion")
                        .WithMany()
                        .HasForeignKey("IdEtapaOrdenProduccion")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Core.Dominio.AggregatesModel.OrdenProduccion", "OrdenProduccion")
                        .WithMany("OrdenProduccionEventos")
                        .HasForeignKey("IdOrdenProduccion")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("EtapaOrdenProduccion");

                    b.Navigation("OrdenProduccion");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.ProveedorArticulo", b =>
                {
                    b.HasOne("Core.Dominio.AggregatesModel.Articulo", "Articulo")
                        .WithMany("ProveedoresArticulo")
                        .HasForeignKey("IdArticulo")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Core.Dominio.AggregatesModel.Proveedor", "Proveedor")
                        .WithMany("ProveedorArticulos")
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.ProveedorArticuloCuentaCorriente", b =>
                {
                    b.HasOne("Core.Dominio.AggregatesModel.CompraArticulo", "CompraArticulo")
                        .WithMany()
                        .HasForeignKey("IdCompraArticulo")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Core.Dominio.AggregatesModel.Proveedor", "Proveedor")
                        .WithMany("ProvedorCuentaCorriente")
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CompraArticulo");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.ProveedorArticuloHistorico", b =>
                {
                    b.HasOne("Core.Dominio.AggregatesModel.Articulo", "Articulo")
                        .WithMany("ArticuloHistorico")
                        .HasForeignKey("IdArticulo")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Core.Dominio.AggregatesModel.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.ProveedorInsumo", b =>
                {
                    b.HasOne("Core.Dominio.AggregatesModel.Insumo", "Insumo")
                        .WithMany("ProveedoresInsumo")
                        .HasForeignKey("IdInsumo")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Core.Dominio.AggregatesModel.Proveedor", "Proveedor")
                        .WithMany("ProveedorInsumos")
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Insumo");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.ProveedorInsumoCuentaCorriente", b =>
                {
                    b.HasOne("Core.Dominio.AggregatesModel.CompraInsumo", "CompraInsumo")
                        .WithMany()
                        .HasForeignKey("IdCompraInsumo")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Core.Dominio.AggregatesModel.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CompraInsumo");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.ProveedorInsumoHistorico", b =>
                {
                    b.HasOne("Core.Dominio.AggregatesModel.Insumo", "Insumo")
                        .WithMany("ProveedoresInsumoHistorico")
                        .HasForeignKey("IdInsumo")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Core.Dominio.AggregatesModel.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Insumo");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.Receta", b =>
                {
                    b.HasOne("Core.Dominio.AggregatesModel.Articulo", "Articulo")
                        .WithMany("Recetas")
                        .HasForeignKey("IdArticulo")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Articulo");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.RecetaDetalle", b =>
                {
                    b.HasOne("Core.Dominio.AggregatesModel.EtapaOrdenProduccion", "EtapaOrdenProduccion")
                        .WithMany("RecetaDetalle")
                        .HasForeignKey("IdEtapaOrdenProduccion")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Core.Dominio.AggregatesModel.Insumo", "Insumo")
                        .WithMany()
                        .HasForeignKey("IdInsumo")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Core.Dominio.AggregatesModel.Receta", "Receta")
                        .WithMany("RecetaDetalles")
                        .HasForeignKey("IdReceta")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("EtapaOrdenProduccion");

                    b.Navigation("Insumo");

                    b.Navigation("Receta");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.Solicitud", b =>
                {
                    b.HasOne("Core.Dominio.AggregatesModel.Sucursal", "Sucursal")
                        .WithMany("Solicitudes")
                        .HasForeignKey("IdSucursal")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.SolicitudDetalle", b =>
                {
                    b.HasOne("Core.Dominio.AggregatesModel.Articulo", "Articulo")
                        .WithMany()
                        .HasForeignKey("IdArticulo")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Core.Dominio.AggregatesModel.Solicitud", "Solicitud")
                        .WithMany("SolicitudDetalles")
                        .HasForeignKey("IdSolicitud")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.SolicitudEvento", b =>
                {
                    b.HasOne("Core.Dominio.AggregatesModel.Solicitud", "Solicitud")
                        .WithMany("SolicitudEventos")
                        .HasForeignKey("IdSolicitud")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.Venta", b =>
                {
                    b.HasOne("Core.Dominio.AggregatesModel.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Core.Dominio.AggregatesModel.Sucursal", "Sucursal")
                        .WithMany("Ventas")
                        .HasForeignKey("IdSucursal")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Core.Dominio.AggregatesModel.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Sucursal");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.VentaDetalle", b =>
                {
                    b.HasOne("Core.Dominio.AggregatesModel.Articulo", "Articulo")
                        .WithMany()
                        .HasForeignKey("IdArticulo")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Core.Dominio.AggregatesModel.Venta", "Venta")
                        .WithMany("VentaDetalles")
                        .HasForeignKey("IdVenta")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.Articulo", b =>
                {
                    b.Navigation("ArticuloHistorico");

                    b.Navigation("ArticuloStock");

                    b.Navigation("ProveedoresArticulo");

                    b.Navigation("Recetas");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.ArticuloCategoria", b =>
                {
                    b.Navigation("Articulos");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.Cliente", b =>
                {
                    b.Navigation("ClienteCuentaCorriente");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.CompraArticulo", b =>
                {
                    b.Navigation("CompraArticuloDetalles");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.CompraInsumo", b =>
                {
                    b.Navigation("CompraInsumoDetalles");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.EtapaOrdenProduccion", b =>
                {
                    b.Navigation("RecetaDetalle");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.Insumo", b =>
                {
                    b.Navigation("ProveedoresInsumo");

                    b.Navigation("ProveedoresInsumoHistorico");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.OrdenProduccion", b =>
                {
                    b.Navigation("OrdenProduccionEventos");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.Proveedor", b =>
                {
                    b.Navigation("ProvedorCuentaCorriente");

                    b.Navigation("ProveedorArticulos");

                    b.Navigation("ProveedorInsumos");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.Receta", b =>
                {
                    b.Navigation("RecetaDetalles");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.Solicitud", b =>
                {
                    b.Navigation("SolicitudDetalles");

                    b.Navigation("SolicitudEventos");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.SolicitudDetalle", b =>
                {
                    b.Navigation("OrdenesProduccion");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.Sucursal", b =>
                {
                    b.Navigation("ArticulosStock");

                    b.Navigation("CajaSucursal");

                    b.Navigation("CompraArticulos");

                    b.Navigation("Solicitudes");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("Core.Dominio.AggregatesModel.Venta", b =>
                {
                    b.Navigation("VentaDetalles");
                });
#pragma warning restore 612, 618
        }
    }
}
